baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'WEN'
theme = 'diary'

[params]
# Add list of sections that should show up on the homepage

#[[menu.main]]
#name = "About"
#url = "/about"
#weight = 2

[deployment]

[[deployment.targets]]
# An arbitrary name for this target.
name = "production"

# Amazon Web Services S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://hello-wen?region=ap-northeast-1"
